#!/bin/sh
# snapper unit for vm-helper
# Configure snapper for filesystem snapshots
#
# The MIT License (MIT)
#
# Copyright (c) 2014 Aron Xu <aron@debian.org>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

[ -s $DATA_ROOT/lib/helper-functions ] && . $DATA_ROOT/lib/helper-functions

SUBVOL_LIST="/ /var/www /var/lib"

snap_dir2subvol ()
{
    local DIR_NAME=$1
    if [ "$DIR_NAME" = "/" ]; then
        return;
    else
        local DIR_FORGED=$(echo $DIR_NAME | sed 's/^\///')
    fi
    if [ ! -d $DIR_NAME ]; then
        btrfs subvol create $DIR_NAME
    elif ! `btrfs subvol list / | grep $DIR_FORGED > /dev/null`; then
        mv $DIR_NAME ${DIR_NAME}.bak
        btrfs subvol create $DIR_NAME
        cp -r ${DIR_NAME}.bak/* $DIR_NAME/ && rm -r ${DIR_NAME}.bak
    fi
}

unit_snapper_common ()
{
    if ! mount | grep '/ ' | grep btrfs > /dev/null; then
        syslog_logger "I: unit_snapper: rootfs is not btrfs, do nothing"
        exit 0
    fi
}

unit_snapper_prep ()
{
    unit_snapper_common

    echo "I: unit_snapper: enabled"
    for i in $SUBVOL_LIST; do
        snap_dir2subvol $i
        if [ "$i" = "/" ]; then
            local SNAP_CONF=root
        else
            local SNAP_CONF=$(echo $i | sed 's/^\///;s/\//_/')
        fi
        if ! `snapper list-configs | grep $SNAP_CONF > /dev/null`; then
            snapper -c $SNAP_CONF create-config $i
        fi
    done

    snapper -c root set-config \
      NUMBER_LIMIT=20 \
      TIMELINE_LIMIT_HOURLY=2 \
      TIMELINE_LIMIT_DAILY=10 \
      TIMELINE_LIMIT_MONTHLY=4 \
      TIMELINE_LIMIT_YEARLY=2
}

unit_snapper_deploy ()
{
    syslog_logger "I: unit_snapper: enabled"
}

# Execution starts
case $1 in
    deploy)
        unit_snapper_deploy
        ;;
    prep)
        unit_snapper_prep
        ;;
    *)
        if check_interactive; then
            printf "unit_snapper: Argument required, possible values:\n deploy prep\n"
        else
            syslog_logger "E: unit_snapper: argument required"
        fi
        ;;
esac
