#!/bin/sh
# ssh unit for vm-helper
# Remove SSH server keys and generate new ones on first boot
#
# The MIT License (MIT)
#
# Copyright (c) 2014 Aron Xu <aron@debian.org>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

unit_ssh_prep()
{
    if `dpkg -l openssh-server 1>/dev/null 2>&1` || `rpm -q openssh-server 1>/dev/null 2>&1`; then
        rm -f /etc/ssh/ssh_host_*_key*
    fi
}

unit_ssh_deploy ()
{
    local KEY_PATH=/etc/ssh/ssh_host_ecdsa_key
    # For Debian based systems
    if `which dpkg-reconfigure >/dev/null 2>&1` && [ ! -s $KEY_PATH ]; then
        dpkg-reconfigure openssh-server
    fi
}

# Execution starts
case $1 in
    deploy)
        unit_ssh_deploy
        ;;
    prep)
        unit_ssh_prep
        ;;
    *)
        printf "unit_ssh: Argument required, possible values:\n deploy prep\n"
        ;;
esac
