#!/bin/sh
# syslog unit for vm-helper
# Handling of logrotate and removal of unwanted log files
#
# The MIT License (MIT)
#
# Copyright (c) 2014 Aron Xu <aron@debian.org>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

[ -s $DATA_ROOT/lib/helper-functions ] && . $DATA_ROOT/lib/helper-functions

unit_syslog_prep ()
{
    echo "I: unit_syslog: enabled"
    if ! `grep xz /etc/logrotate.conf > /dev/null`; then
        printf "compresscmd /usr/bin/xz\nuncompresscmd /usr/bin/unxz\ncompressext .xz" >> /etc/logrotate.conf
    fi

    find /var/log -name *[0-9]* -delete

    for i in /var/log/messages /var/log/syslog /var/log/*.log; do
        echo > $i;
    done
}

unit_syslog_deploy ()
{
    syslog_logger "I: unit_syslog: enabled"
}

# Execution starts
case $1 in
    deploy)
	unit_syslog_deploy
        ;;
    prep)
        unit_syslog_prep
        ;;
    *)
        if check_interactive; then
            printf "unit_syslog: Argument required, possible values:\n deploy prep\n"
        else
            syslog_logger "E: unit_syslog: argument required"
        fi
        ;;
esac
