#!/bin/sh
# selinux unit for vm-helper
# Require SELinux to be enabled all the time, use Enforcing mode as default.
#
# The MIT License (MIT)
#
# Copyright (c) 2014 Aron Xu <aron@debian.org>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

[ -s $DATA_ROOT/lib/helper-functions ] && . $DATA_ROOT/lib/helper-functions

SELINUX_LOCAL=$CONF_DATA
SELINUX_MODULE=vm_policy

unit_selinux_audit2allow ()
{
    # This generates a Type Enforcement (.te) file as well as a binary
    # Policy Package (.pp) file to be loaded (semodule -i).
    #
    # ausearch is used because some log may not appear in audit.log in time.
    #
    cd $SELINUX_LOCAL
    ausearch -m avc | audit2allow -M $SELINUX_MODULE
}

unit_selinux_compile_te ()
{
    # Compile and package Type Enforcement file
    #
    cd $SELINUX_LOCAL
    checkmodule -M -m -o ${SELINUX_MODULE}.mod ${SELINUX_MODULE}.te
    semodule_package -o ${SELINUX_MODULE}.pp -m ${SELINUX_MODULE}.mod
    rm -f ${SELINUX_MODULE}.mod
}

unit_selinux_load_pp ()
{
    # Load Policy Package module file
    #
    cd $SELINUX_LOCAL
    semodule -i ${SELINUX_MODULE}.pp
}

unit_selinux_common ()
{
    if `which selinux-activate > /dev/null`; then
        if ! `grep '^FSCKFIX' /etc/default/rcS > /dev/null`; then
            echo "FSCKFIX=yes" >> /etc/default/rcS
        fi
    fi
}

unit_selinux_prep()
{
    unit_selinux_common
    unit_selinux_compile_te
    unit_selinux_load_pp

    selinux-activate
    selinux-config-enforcing
}

unit_selinux_deploy ()
{
    unit_selinux_common
    chmod 0400 /proc/kallsyms

    if `which selinuxenabled > /dev/null`; then
        if `selinuxenabled`; then
            local SE_MODE=`getenforcing`
            if [ "$SE_MODE" = "Enforcing" ]; then
                printf "I: unit_selinux: SELinux enabled, current mode $SE_MODE.\n"
            else
                printf "I: unit_selinux: SELinux enabled, current mode $SE_MODE, while Enforcing mode is recommended.\n"
            fi
        else
            unit_selinux_prep
            printf "W: unit_selinux: SELinux disabled, this is not expected, try to re-enable with Enforcing mode at next boot.\n"
        fi
    fi
}

# Execution starts
case $1 in
    deploy)
        unit_selinux_deploy
        ;;
    prep)
        unit_selinux_prep
        ;;
    *)
        printf "unit_selinux: Argument required, possible values:\n deploy prep\n"
        ;;
esac
