#!/bin/sh
set -e

#DEBHELPER#

helper_unit_disable ()
{
UNIT_LIST=$(vm-helper list)

for i in $UNIT_LIST; do
	vm-helper disable $i;
done
}

case "$1" in
	remove|purge)
		helper_unit_disable
		rm -f /etc/vm-helper/deploy-not-completed
		;;
	upgrade|abort-upgrade|abort-remove|abort-deconfigure)
		;;
	*)
		echo "prerm called with unknown argument \`$1'" >&2
		exit 1
		;;
esac
